### ISSUE TITLE
Attachment download from inside a metadata record fails to load

### ISSUE THREAD

**Issue by keaves** [aodn/core-geonetwork#34]
Steps to reproduce
1. Search geonetwork for a metadata record with data for download
2. Click into the record and scroll down to the OnLine resource: Data for download link
3. Download an attachment imbeded in geonetwork (not an external download link)

What should happen
A file disclaimer appears asking for name, email address, etc:
![image](https://cloud.githubusercontent.com/assets/10750046/6795435/d3b4ab76-d233-11e4-807d-f726acf1565b.png)

What does happen
The licensing and disclaimer window does not load.
![image](https://cloud.githubusercontent.com/assets/10750046/6795477/6639da0c-d234-11e4-849e-04dc215e99af.png)

It appears to be related to the code:
function runFileDownloadSummary(a,c){pars="&uuid="+a;
var b=new Ajax.Request(getGNServiceURL("prepare.file.download"),{method:"get",parameters:pars,onSuccess:function(d){Modalbox.show(d.responseText,{title:c,height:400,width:600})

This code may be generating a duplicated URL as follows: 
http://metadata.imas.utas.edu.au/geonetwork/srv/eng/http://metadata.imas.utas.edu.au/geonetwork/srv/en/file.disclaimer?uuid=73065eb8-b6f8-4c3c-bf0f-6d4be8b708c9&fname=Biodiversity_degradation_blackriverdataset.xlsx&access=private

Instead of:
http://metadata.imas.utas.edu.au/geonetwork/srv/en/file.disclaimer?uuid=73065eb8-b6f8-4c3c-bf0f-6d4be8b708c9&fname=Biodiversity_degradation_blackriverdataset.xlsx&access=private
Which works

**Comment by jonescc** [comment]
Fixed by https://github.com/aodn/core-geonetwork/issues/52
