### ISSUE TITLE
Failure to load local schema.xsd on latest Geonetwork.war

### ISSUE THREAD

**Issue by stevenvandervalk** [aodn/core-geonetwork#40]
Hi,

We've on the RDS project to contribute data to AODN using various services.  Am posting in hope someone else using Geonetwork can assist with an error we can't seem to solve.

Geonetwork error : 
`Raised exception while starting appl handler. Skipped.
Message		Failed whilst validating schema-ident file /usr/share/tomcat/webapps/geonetwork##2.10.3/WEB-INF/data/config/schema_plugins/iso19115/schema-ident.xml. Exception message if any is XSD Validation error(s): <xsderrors>
 <error>
 <typeOfError>WARNING</typeOfError>
 <errorNumber>1</errorNumber>
 <message>schema_reference.4: Failed to read schema document 'http://geonetwork-opensource.org/schemas/schema-ident/schema-ident.xsd', because 1) could not find the document; 2) the document could not be read; 3) the root element of the document is not &lt;xsd:schema&gt;. (Element: gns:schema with parent element: /)</message>
 <xpath>.</xpath>
 </error>
`

The AODN recommended Jenkins build of `geonetwork.war` 
* https://jenkins.aodn.org.au/job/GeoNetwork_prod/lastSuccessfulBuild/artifact/web/target/geonetwork.war)

works perfectly out of the box on several vagrant builds and distros but unfortunately runs into an error on our SaltStack configured Centos 7.1 ( distro we have to use in production).

It seems the system property `xml.catalog.files` -  despite being set -
` 
[jeeves.apphand] - jeeves.xml.catalog.files property set to /usr/share/tomcat/webapps/g
eonetwork##2.10.3/WEB-INF/oasis-catalog.xml;
`

Is not redirecting requests to the remote location of `schema-ident.xsd` (geonetwork-opensource.org) to the local file path.

Unfortunately scouring the web it appears years ago and since fixed in Geonetwork trunk.
* http://sourceforge.net/p/geonetwork/mailman/message/29525723/
* http://osgeo-org.1560.x6.nabble.com/Schemas-are-not-loading-SEC-UNCLASSIFIED-td3860510.html

Any help or advice would be greatly appreciated!

cc @danielbaird @justberkhout

**Comment by pmbohm** [comment]
Are there any crazy permissions or ACL's on the local file paths to schema-ident.xsd or even oasis-catalog.xml ?

**Comment by stevenvandervalk** [comment]
Thanks for the reply!  
* When comparing a working geonetwork on centos 7 on metal vs the error-ing vagrant install everything in `/usr/share/tomcat/` and `var/lib/tomcat` matches up and is either `root:tomcat` or  `tomcat:tomcat`.
* the tomcat user is able to `sudo cat /usr/share/tomcat/webapps/geonetwork/WEB-INF/oasis-catalog.xml` and `schema-ident.xsd`, which I think is the user geonetwork uses to read those files.
* I'm not unsure about ACL's other than using `getfacl` saying nothing is set on/in those directories?
* SELinux off.

I initially thought the XML parsing (either xsd or the redirect) was to blame but a vanilla build using the same machine image by hand works just fine, so it seems to be strangely saltstack produced. Does anyone else use a config management tool to deploy geonetwork? 

Not sure how else to effectively debug.  Is there a place in geonetwork where you can change the original request to `geonetwork-opensource.org` to be another explicitly local path besides the mapping? Can I change/off the schema validation?

Thanks for your help!

**Comment by danfruehauf** [comment]
@stevenvandervalk GN gives us all pain. I'm not going to be much of a help here, but regarding configuration management, we use Chef to deploy GN (and manage our whole infrastructure). If you'd like, we can potentially open our Chef repo for you so you can experiment with it. A simple `vagrant up` command will get our whole stack running on an Ubuntu 12.04 box.

**Comment by stevenvandervalk** [comment]
Thanks @danfruehauf.  Read access to compare against would be a great help!

**Comment by danfruehauf** [comment]
@stevenvandervalk Just sent you an invite. You can join us on #imos on Freenode (IRC), I can give you more detailed instructions on how to setup things, although the README file should be good too.

**Comment by stevenvandervalk** [comment]
Thanks. I'll give it a try and see you next week on IRC.

**Comment by jonescc** [comment]
@stevenvandervalk or @danfruehauf, is this still an issue?

**Comment by danfruehauf** [comment]
Haven't heard from @stevenvandervalk. Any news regarding that?

**Comment by stevenvandervalk** [comment]
Sorry away for a while. Feel free to close and I'll reopen if need. Thanks.

Sent from my phone
0468311883

On 5 Jan 2016, at 23:45, Dan Fruehauf <notifications@github.com<mailto:notifications@github.com>> wrote:


Haven't heard from @stevenvandervalk<https://github.com/stevenvandervalk>. Any news regarding that?

-
